/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cbse_ip_project_hospital_management;

/**
 *
 * @author Jithu G Panicker
 */
public class aboutScreen_GUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form aboutScreen_GUI
     */
    public aboutScreen_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeBTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(987, 508));
        getContentPane().setLayout(null);

        closeBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        closeBTN.setText("CLOSE");
        closeBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });
        getContentPane().add(closeBTN);
        closeBTN.setBounds(790, 400, 170, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/aboutPage.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 990, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBTN;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
