/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cbse_ip_project_hospital_management;

/**
 *
 * @author Jithu G Panicker
 */
public class DefaultScreen_GUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form DefaultScreen_GUI
     */
    public DefaultScreen_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(987, 508));
        setMinimumSize(new java.awt.Dimension(987, 508));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(987, 508));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/mainPage.jpg"))); // NOI18N
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
