/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cbse_ip_project_hospital_management;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jithu G Panicker
 */
public class DoctorScreenLocal_GUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form doctorScreenLocal
     */
    DoctorScreenLocal_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        docTBL = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        dnameSearchRB = new javax.swing.JRadioButton();
        dcodeSearchRB = new javax.swing.JRadioButton();
        dphoneSearchRB = new javax.swing.JRadioButton();
        deptSearchRB = new javax.swing.JRadioButton();
        searchBTN = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        dnameSortRB = new javax.swing.JRadioButton();
        dcodeSortRB = new javax.swing.JRadioButton();
        sortBTN = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        ascRB = new javax.swing.JRadioButton();
        descRB = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        refreshBTN = new javax.swing.JButton();
        closeBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(987, 508));
        setMinimumSize(new java.awt.Dimension(987, 508));
        setPreferredSize(new java.awt.Dimension(987, 508));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        docTBL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        docTBL.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        docTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Code", "Doctor Name", "Department", "Consultation Fee", "Gender", "Phone No."
            }
        ));
        docTBL.setDoubleBuffered(true);
        jScrollPane1.setViewportView(docTBL);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(18, 20, 935, 123);

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Search by"));

        buttonGroup3.add(dnameSearchRB);
        dnameSearchRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dnameSearchRB.setText("Doctor Name");

        buttonGroup3.add(dcodeSearchRB);
        dcodeSearchRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dcodeSearchRB.setText("Doctor Code");

        buttonGroup3.add(dphoneSearchRB);
        dphoneSearchRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dphoneSearchRB.setText("Phone No.");

        buttonGroup3.add(deptSearchRB);
        deptSearchRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        deptSearchRB.setText("Department");
        deptSearchRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptSearchRBActionPerformed(evt);
            }
        });

        searchBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        searchBTN.setText("SEARCH");
        searchBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(deptSearchRB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dphoneSearchRB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dcodeSearchRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dnameSearchRB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(dcodeSearchRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dnameSearchRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deptSearchRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dphoneSearchRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchBTN)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sort by"));

        buttonGroup1.add(dnameSortRB);
        dnameSortRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dnameSortRB.setText("Doctor Name");

        buttonGroup1.add(dcodeSortRB);
        dcodeSortRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dcodeSortRB.setText("Doctor Code");

        sortBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        sortBTN.setText("SORT");
        sortBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sortBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBTNActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        buttonGroup2.add(ascRB);
        ascRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        ascRB.setText("Ascending");

        buttonGroup2.add(descRB);
        descRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        descRB.setText("Descending");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ascRB)
                    .addComponent(descRB))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(ascRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descRB))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(dnameSortRB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sortBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcodeSortRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(dcodeSortRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dnameSortRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        refreshBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        refreshBTN.setText("REFRESH");
        refreshBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        refreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBTNActionPerformed(evt);
            }
        });

        closeBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        closeBTN.setText("CLOSE");
        closeBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refreshBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeBTN))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8);
        jPanel8.setBounds(20, 160, 370, 290);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/docDetails(Local).jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -30, 1010, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
       DefaultTableModel dtm = (DefaultTableModel) docTBL.getModel();
        String searchBy = "";
        String item = "";
        if (dnameSearchRB.isSelected()) {
            searchBy = "Doctor_Name";
            item = JOptionPane.showInputDialog(rootPane, "Enter Doctor Name to search");
        } else if (dcodeSearchRB.isSelected()) {
            searchBy = "Doctor_Code";
            item = JOptionPane.showInputDialog(rootPane, "Enter Doctor Code to search");
        } else if (dphoneSearchRB.isSelected()) {
            searchBy = "Phone_Number";
            item = JOptionPane.showInputDialog(rootPane, "Enter Phone Number to search");
        } else if (deptSearchRB.isSelected()) {
            searchBy = "Department";
            item = JOptionPane.showInputDialog(rootPane, "Enter Department to search");
        }
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db", "root", "pass");
            Statement stmt = (Statement) con.createStatement();
            String str="Select * from docDetails where "+searchBy+" like '%"+item+"%'";
            ResultSet rs = stmt.executeQuery(str);
            String docCode, docName, gender, docDept, docCons, docPhone;
            if(rs.next()==false){
                JOptionPane.showMessageDialog(rootPane, "No matching record found");
                refreshBTN.doClick();
            }
            rs.beforeFirst();
            while (rs.next()) {
                docCode = rs.getString("Doctor_Code");
                docName = rs.getString("Doctor_Name");
                docDept = rs.getString("Department");
                gender = rs.getString("Gender");
                docCons = rs.getString("Consultation_Fee");
                docPhone = rs.getString("Phone_Number");
                Object newRow[] = {docCode, docName, docDept, gender, docCons, docPhone};
                dtm.addRow(newRow);
            } 
            
            stmt.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_searchBTNActionPerformed

    private void sortBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBTNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel)docTBL.getModel();
        String sortBy="";
        String sortType="";
        if(dcodeSortRB.isSelected()){
            sortBy="Doctor_Code";
        } else if (dnameSortRB.isSelected()){
            sortBy="Doctor_Name";
        }
        if(ascRB.isSelected()){
            sortType="asc";
        }else if(descRB.isSelected()){
            sortType="desc";
        }
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db","root","pass");
            Statement stmt=(Statement)con.createStatement();
            String str="Select * from docDetails order by "+sortBy+" "+sortType;
            ResultSet rs=stmt.executeQuery(str);
            String docCode,docName,gender,docDept,docCons,docPhone;
            while(docTBL.getRowCount()>0){
                dtm.removeRow(0);
            }
            while(rs.next()){
                docCode=rs.getString(1);
                docName=rs.getString(2);
                docDept=rs.getString(3);
                gender=rs.getString(4);
                docCons=rs.getString(5);
                docPhone=rs.getString(6);
                Object newRow[]={docCode,docName,docDept,gender,docCons,docPhone};
                dtm.addRow(newRow);
            }
            stmt.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_sortBTNActionPerformed

    private void refreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTNActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel dtm =(DefaultTableModel)docTBL.getModel();
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db","root","pass");
            Statement refreshStmt=(Statement)con.createStatement();
            String str="Select * from docDetails";
            ResultSet rs=refreshStmt.executeQuery(str);
            String docCode,docName,gender,docDept,docCons,docPhone;
            while(docTBL.getRowCount()>0){
                dtm.removeRow(0);
            }
            while(rs.next()){
                docCode=rs.getString(1);
                docName=rs.getString(2);
                docDept=rs.getString(3);
                gender=rs.getString(4);
                docCons=rs.getString(5);
                docPhone=rs.getString(6);
                Object newRow[]={docCode,docName,docDept,gender,docCons,docPhone};
                dtm.addRow(newRow);
            }
            rs.close();
            refreshStmt.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
    }//GEN-LAST:event_refreshBTNActionPerformed

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeBTNActionPerformed

    private void deptSearchRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptSearchRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptSearchRBActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        refreshBTN.doClick();
        dcodeSortRB.setSelected(true);
        ascRB.setSelected(true);
        dcodeSearchRB.setSelected(true);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ascRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton closeBTN;
    private javax.swing.JRadioButton dcodeSearchRB;
    private javax.swing.JRadioButton dcodeSortRB;
    private javax.swing.JRadioButton deptSearchRB;
    private javax.swing.JRadioButton descRB;
    private javax.swing.JRadioButton dnameSearchRB;
    private javax.swing.JRadioButton dnameSortRB;
    private javax.swing.JTable docTBL;
    private javax.swing.JRadioButton dphoneSearchRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JButton sortBTN;
    // End of variables declaration//GEN-END:variables
}
