/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cbse_ip_project_hospital_management;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jithu G Panicker
 */
public class DoctorScreenAdmin_GUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form DoctorScreenAdmin_GUI
     */
    public DoctorScreenAdmin_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    void modifyOn() {
        addBTN.setEnabled(false);
        clearBTN.setEnabled(false);
        closeBTN.setEnabled(false);
        refreshBTN.setEnabled(false);
        deleteBTN.setEnabled(false);
        modifyBTN.setEnabled(false);
        sortBTN.setEnabled(false);
        searchBTN.setEnabled(false);
        saveBTN.setEnabled(true);
        cancelBTN.setEnabled(true);
    }

    void modifyOff() {
        saveBTN.setEnabled(false);
        cancelBTN.setEnabled(false);
        addBTN.setEnabled(true);
        clearBTN.setEnabled(true);
        closeBTN.setEnabled(true);
        refreshBTN.setEnabled(true);
        deleteBTN.setEnabled(true);
        modifyBTN.setEnabled(true);
        sortBTN.setEnabled(true);
        searchBTN.setEnabled(true);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        dnameSearchRB = new javax.swing.JRadioButton();
        dcodeSearchRB = new javax.swing.JRadioButton();
        dphoneSearchRB = new javax.swing.JRadioButton();
        deptSearchRB = new javax.swing.JRadioButton();
        searchBTN = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        dnameSortRB = new javax.swing.JRadioButton();
        dcodeSortRB = new javax.swing.JRadioButton();
        sortBTN = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        ascRB = new javax.swing.JRadioButton();
        descRB = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        refreshBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        closeBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dcodeTXT = new javax.swing.JTextField();
        dnameTXT = new javax.swing.JTextField();
        dphoneTXT = new javax.swing.JTextField();
        dconsTXT = new javax.swing.JTextField();
        deptCB = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        maleRB = new javax.swing.JRadioButton();
        femaleRB = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        cancelBTN = new javax.swing.JButton();
        modifyBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        docTBL = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(987, 508));
        setMinimumSize(new java.awt.Dimension(987, 508));
        setPreferredSize(new java.awt.Dimension(987, 508));
        setRequestFocusEnabled(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setMaximumSize(new java.awt.Dimension(987, 508));
        jPanel7.setMinimumSize(new java.awt.Dimension(987, 508));
        jPanel7.setPreferredSize(new java.awt.Dimension(987, 508));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Search by"));

        buttonGroup4.add(dnameSearchRB);
        dnameSearchRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dnameSearchRB.setText("Doctor Name");

        buttonGroup4.add(dcodeSearchRB);
        dcodeSearchRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dcodeSearchRB.setText("Doctor Code");
        dcodeSearchRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcodeSearchRBActionPerformed(evt);
            }
        });

        buttonGroup4.add(dphoneSearchRB);
        dphoneSearchRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dphoneSearchRB.setText("Phone No.");

        buttonGroup4.add(deptSearchRB);
        deptSearchRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        deptSearchRB.setText("Department");
        deptSearchRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptSearchRBActionPerformed(evt);
            }
        });

        searchBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        searchBTN.setText("SEARCH");
        searchBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(searchBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(deptSearchRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dphoneSearchRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcodeSearchRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dnameSearchRB, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dcodeSearchRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dnameSearchRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deptSearchRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dphoneSearchRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sort by"));

        buttonGroup2.add(dnameSortRB);
        dnameSortRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dnameSortRB.setText("Doctor Name");

        buttonGroup2.add(dcodeSortRB);
        dcodeSortRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dcodeSortRB.setText("Doctor Code");

        sortBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        sortBTN.setText("SORT");
        sortBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sortBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBTNActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        buttonGroup3.add(ascRB);
        ascRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        ascRB.setText("Ascending");

        buttonGroup3.add(descRB);
        descRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        descRB.setText("Descending");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ascRB)
                    .addComponent(descRB))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(ascRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descRB))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(dnameSortRB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sortBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcodeSortRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(dcodeSortRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dnameSortRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        refreshBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        refreshBTN.setText("REFRESH");
        refreshBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        refreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBTNActionPerformed(evt);
            }
        });

        deleteBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        deleteBTN.setText("DELETE");
        deleteBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        closeBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        closeBTN.setText("CLOSE");
        closeBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });

        clearBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        clearBTN.setText("CLEAR");
        clearBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refreshBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(clearBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeBTN)
                    .addComponent(clearBTN))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel8);
        jPanel8.setBounds(590, 150, 360, 310);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Add Doctor Details"));

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel1.setText("Doctor Code");

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel2.setText("Doctor Name");

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel3.setText("Department");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel4.setText("Consultation");

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel5.setText("Phone No.");

        dcodeTXT.setEditable(false);
        dcodeTXT.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dcodeTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcodeTXTActionPerformed(evt);
            }
        });

        dnameTXT.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dnameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnameTXTActionPerformed(evt);
            }
        });

        dphoneTXT.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dphoneTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dphoneTXTActionPerformed(evt);
            }
        });

        dconsTXT.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dconsTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dconsTXTActionPerformed(evt);
            }
        });

        deptCB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        deptCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cardiology", "Dermatology", "Endocrinology", "ENT", "Gastroenterology", "GP", "Gynecology", "Hepatology ", "Neonatology ", "Nephrology ", "Neurology ", "Ophthalmology ", "Orthopaedic", "Pathology", "Paediatric", "Physiatry ", "Pulmonology", "Psychiatry", "Rheumatology", "Urology" }));
        deptCB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deptCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptCBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel6.setText("Gender");

        buttonGroup1.add(maleRB);
        maleRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        maleRB.setText("Male");
        maleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(femaleRB);
        femaleRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        femaleRB.setText("Female");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        cancelBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        cancelBTN.setText("CANCEL");
        cancelBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTNActionPerformed(evt);
            }
        });

        modifyBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        modifyBTN.setText("MODIFY");
        modifyBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modifyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBTNActionPerformed(evt);
            }
        });

        saveBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        saveBTN.setText("SAVE");
        saveBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        addBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        addBTN.setText("ADD");
        addBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(modifyBTN)
                        .addComponent(saveBTN)
                        .addComponent(cancelBTN))
                    .addComponent(addBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcodeTXT)
                            .addComponent(dnameTXT)
                            .addComponent(dphoneTXT)
                            .addComponent(dconsTXT)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(maleRB)
                                .addGap(32, 32, 32)
                                .addComponent(femaleRB)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(deptCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(8, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dcodeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dnameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(deptCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dconsTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(maleRB)
                    .addComponent(femaleRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dphoneTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 160, 400, 270);

        docTBL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        docTBL.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        docTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Code", "Doctor Name", "Department", "Gender", "Consultation Fee", "Phone No."
            }
        ));
        docTBL.setDoubleBuffered(true);
        jScrollPane1.setViewportView(docTBL);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 17, 940, 123);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/docDetailsAdmin.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -80, 1080, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dcodeSearchRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcodeSearchRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcodeSearchRBActionPerformed

    private void deptSearchRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptSearchRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptSearchRBActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
         DefaultTableModel dtm = (DefaultTableModel) docTBL.getModel();
        String searchBy = "";
        String item = "";
        if (dnameSearchRB.isSelected()) {
            searchBy = "Doctor_Name";
            item = JOptionPane.showInputDialog(rootPane, "Enter Doctor Name to search");
        } else if (dcodeSearchRB.isSelected()) {
            searchBy = "Doctor_Code";
            item = JOptionPane.showInputDialog(rootPane, "Enter Doctor Code to search");
        } else if (dphoneSearchRB.isSelected()) {
            searchBy = "Phone_Number";
            item = JOptionPane.showInputDialog(rootPane, "Enter Phone Number to search");
        } else if (deptSearchRB.isSelected()) {
            searchBy = "Department";
            item = JOptionPane.showInputDialog(rootPane, "Enter Department to search");
        }
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db", "root", "pass");
            Statement stmt = (Statement) con.createStatement();
            String str="Select * from docDetails where "+searchBy+" like '%"+item+"%'";
            ResultSet rs = stmt.executeQuery(str);
            String docCode, docName, gender, docDept, docCons, docPhone;
            if(rs.next()==false){
                JOptionPane.showMessageDialog(rootPane, "No matching record found");
                refreshBTN.doClick();
            }
            rs.beforeFirst();
            while (rs.next()) {
                docCode = rs.getString("Doctor_Code");
                docName = rs.getString("Doctor_Name");
                docDept = rs.getString("Department");
                gender = rs.getString("Gender");
                docCons = rs.getString("Consultation_Fee");
                docPhone = rs.getString("Phone_Number");
                Object newRow[] = {docCode, docName, docDept, gender, docCons, docPhone};
                dtm.addRow(newRow);
            } 
            
            stmt.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_searchBTNActionPerformed

    private void sortBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBTNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel)docTBL.getModel();
        String sortBy="";
        String sortType="";
        if(dcodeSortRB.isSelected()){
            sortBy="Doctor_Code";
        } else if (dnameSortRB.isSelected()){
            sortBy="Doctor_Name";
        }
        if(ascRB.isSelected()){
            sortType="asc";
        }else if(descRB.isSelected()){
            sortType="desc";
        }
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db","root","pass");
            Statement stmt=(Statement)con.createStatement();
            String str="Select * from docDetails order by "+sortBy+" "+sortType;
            ResultSet rs=stmt.executeQuery(str);
            String docCode,docName,gender,docDept,docCons,docPhone;
            while(docTBL.getRowCount()>0){
                dtm.removeRow(0);
            }
            while(rs.next()){
                docCode=rs.getString(1);
                docName=rs.getString(2);
                docDept=rs.getString(3);
                gender=rs.getString(4);
                docCons=rs.getString(5);
                docPhone=rs.getString(6);
                Object newRow[]={docCode,docName,docDept,gender,docCons,docPhone};
                dtm.addRow(newRow);
            }
            stmt.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_sortBTNActionPerformed

    private void refreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTNActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel dtm=(DefaultTableModel)docTBL.getModel();
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db","root","pass");
            Statement refreshStmt=(Statement)con.createStatement();
            String str="Select * from docDetails";
            ResultSet rs=refreshStmt.executeQuery(str);
            String docCode="",docName,gender,docDept,docCons,docPhone;
            while(docTBL.getRowCount()>0){
                dtm.removeRow(0);
            }
            while(rs.next()){
                docCode=rs.getString(1);
                docName=rs.getString(2);
                docDept=rs.getString(3);
                gender=rs.getString(4);
                docCons=rs.getString(5);
                docPhone=rs.getString(6);
                Object newRow[]={docCode,docName,docDept,gender,docCons,docPhone};
                dtm.addRow(newRow);
            }
            int i=Integer.parseInt(docCode);
            i++;
            dcodeTXT.setText(""+i);
            rs.close();
            refreshStmt.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        deptCB.setSelectedIndex(0);
    }//GEN-LAST:event_refreshBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        String dc=JOptionPane.showInputDialog(rootPane,"Enter Doctor Code to be deleted");
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db","root","pass");
            Statement stmt=(Statement)con.createStatement();
            String str2="Select * from docDetails where Doctor_Code='"+dc+"'";
            ResultSet rs2=stmt.executeQuery(str2);
            if(rs2.next()==false){
                JOptionPane.showMessageDialog(rootPane, "No matching record found");
                refreshBTN.doClick();
            }
            rs2.close();
            String str="Delete from docDetails where Doctor_Code='"+dc+"'";
            stmt.executeUpdate(str);
            stmt.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        refreshBTN.doClick();
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        refreshBTN.doClick();
        dphoneTXT.setText("");
        dnameTXT.setText("");
        maleRB.setSelected(true);
        deptCB.setSelectedIndex(0);
        dconsTXT.setText("");
        dcodeSortRB.setSelected(true);
        ascRB.setSelected(true);
        dcodeSearchRB.setSelected(true);
    }//GEN-LAST:event_clearBTNActionPerformed

    private void dcodeTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcodeTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcodeTXTActionPerformed

    private void dnameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dnameTXTActionPerformed

    private void dphoneTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dphoneTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dphoneTXTActionPerformed

    private void dconsTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dconsTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dconsTXTActionPerformed

    private void deptCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptCBActionPerformed

    private void maleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRBActionPerformed

    private void cancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTNActionPerformed
        // TODO add your handling code here:
        modifyOff();
        clearBTN.doClick();
    }//GEN-LAST:event_cancelBTNActionPerformed

    private void modifyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBTNActionPerformed
        // TODO add your handling code here:
        modifyOn();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db","root","pass");
            Statement modifyStmt=(Statement) con.createStatement();
            String dCode=(String)JOptionPane.showInputDialog(this,"Enter doctor code");
            String str="Select * from docDetails where Doctor_Code='"+dCode+"'";
            ResultSet rs=(ResultSet) modifyStmt.executeQuery(str);
            if(rs.next()){
                dcodeTXT.setText(rs.getString("Doctor_Code"));
                dnameTXT.setText(rs.getString("Doctor_Name"));
                dconsTXT.setText(rs.getString("Consultation_Fee"));
                dphoneTXT.setText(rs.getString("Phone_Number"));
                String gender=rs.getString("Gender");
                deptCB.setSelectedItem(rs.getString("Department"));
                if(gender.equals("Male")){
                    maleRB.setSelected(true);
                }else{
                    femaleRB.setSelected(true);
                }
            }else if(dCode!=null){
                modifyOff();
                clearBTN.doClick();
                JOptionPane.showMessageDialog(this,"Sorry. Record not found in the database","For your kind Information",3);
            }else if(dCode==null){
                modifyOff();
                clearBTN.doClick();
                JOptionPane.showMessageDialog(this,"Sorry. No Doctor Code provided.","For your kind Information",3);
            }
            rs.close();
            modifyStmt.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_modifyBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        String docCode=dcodeTXT.getText();
        String docName=dnameTXT.getText();
        String docPhone=dphoneTXT.getText();
        String docCons=dconsTXT.getText();
        String docDept=(String)deptCB.getSelectedItem();
        String gender="";
        if(maleRB.isSelected()){
            gender="Male";
        }else if(femaleRB.isSelected()){
            gender="Female";
        }
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db","root","pass");
            Statement stmt = (Statement) con.createStatement();
            String str="Update docDetails set Doctor_Name='"+docName+"',Phone_Number="+docPhone+",Consultation_Fee="+docCons+
                       ",Department='"+docDept+"',Gender='"+gender+"'where Doctor_Code='"+docCode+"'";
            stmt.executeUpdate(str);
            stmt.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        modifyOff();
        clearBTN.doClick();
    }//GEN-LAST:event_saveBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        modifyOff();
        String docCode=dcodeTXT.getText();
        String docName=dnameTXT.getText();
        String docPhone=dphoneTXT.getText();
        String docCons=dconsTXT.getText();
        String docDept=(String)deptCB.getSelectedItem();
        String gender="";
            if(maleRB.isSelected()){
                gender="Male";
            }else if(femaleRB.isSelected()){
                gender="Female";
            }
        if(docName.equals("")||docCons.equals("")||docPhone.equals("")) 
            JOptionPane.showMessageDialog(rootPane,"Please fill in all the details.","Warning!!! Error Message",2);
        else{
             try{
                Class.forName("java.sql.DriverManager");
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db","root","pass");
                Statement addStmt=(Statement)con.createStatement();
                String str ="Insert into docDetails values('"+docCode+"','"+docName+"','"+docDept+"','"+gender+"',"+docCons+","+docPhone+")";
                addStmt.executeUpdate(str);
                addStmt.close();
                con.close();
                clearBTN.doClick();
            }catch (Exception e){
                JOptionPane.showMessageDialog(rootPane,e.getMessage());
            }
        }
    }//GEN-LAST:event_addBTNActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        clearBTN.doClick();
        modifyOff();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JRadioButton ascRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton cancelBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton closeBTN;
    private javax.swing.JRadioButton dcodeSearchRB;
    private javax.swing.JRadioButton dcodeSortRB;
    private javax.swing.JTextField dcodeTXT;
    private javax.swing.JTextField dconsTXT;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JComboBox deptCB;
    private javax.swing.JRadioButton deptSearchRB;
    private javax.swing.JRadioButton descRB;
    private javax.swing.JRadioButton dnameSearchRB;
    private javax.swing.JRadioButton dnameSortRB;
    private javax.swing.JTextField dnameTXT;
    private javax.swing.JTable docTBL;
    private javax.swing.JRadioButton dphoneSearchRB;
    private javax.swing.JTextField dphoneTXT;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JButton modifyBTN;
    private javax.swing.JButton refreshBTN;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JButton sortBTN;
    // End of variables declaration//GEN-END:variables
}
