/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main_GUI.java
 *
 * Created on Oct 30, 2013, 9:19:21 PM
 */

package cbse_ip_project_hospital_management;

import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;

/**
 *
 * @author STUDENT
 */
public class Main_GUI extends javax.swing.JFrame {

    /** Creates new form mainScreen */
    public Main_GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    String uID="";
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        statusLBL = new javax.swing.JLabel();
        copyrightLBL = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        homeMenuItem = new javax.swing.JMenuItem();
        logOutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        detailsMenu = new javax.swing.JMenu();
        docDetailsMenuItem = new javax.swing.JMenuItem();
        patDetailsMenuItem = new javax.swing.JMenuItem();
        servicesMenu = new javax.swing.JMenu();
        servicesMenuItem = new javax.swing.JMenuItem();
        reportMenu = new javax.swing.JMenu();
        reportMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apollo Hospitals Administrations");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon("logo.jpg").getImage());
        setMinimumSize(new java.awt.Dimension(1016, 640));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jDesktopPane.setMaximumSize(new java.awt.Dimension(987, 508));
        jDesktopPane.setMinimumSize(new java.awt.Dimension(987, 508));
        jDesktopPane.setName(""); // NOI18N
        getContentPane().add(jDesktopPane);
        jDesktopPane.setBounds(14, 35, 987, 508);

        statusLBL.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        getContentPane().add(statusLBL);
        statusLBL.setBounds(792, 0, 210, 30);

        copyrightLBL.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        copyrightLBL.setText("© 2014 Apollo Hospitals Bangalore");
        getContentPane().add(copyrightLBL);
        copyrightLBL.setBounds(320, 560, 400, 21);
        getContentPane().add(jSeparator);
        jSeparator.setBounds(10, 554, 991, 2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/mainScreen.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1010, 600);

        fileMenu.setText("File");

        homeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_HOME, java.awt.event.InputEvent.ALT_MASK));
        homeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/home.jpg"))); // NOI18N
        homeMenuItem.setText("Home");
        homeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(homeMenuItem);

        logOutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.SHIFT_MASK));
        logOutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/logout.jpg"))); // NOI18N
        logOutMenuItem.setText("Log Out");
        logOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(logOutMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/exit.jpg"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        MenuBar.add(fileMenu);

        detailsMenu.setText("Details");

        docDetailsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        docDetailsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/doc.jpg"))); // NOI18N
        docDetailsMenuItem.setText("Doctor Details");
        docDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docDetailsMenuItemActionPerformed(evt);
            }
        });
        detailsMenu.add(docDetailsMenuItem);

        patDetailsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        patDetailsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/patient.jpg"))); // NOI18N
        patDetailsMenuItem.setText("Patient Details");
        patDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patDetailsMenuItemActionPerformed(evt);
            }
        });
        detailsMenu.add(patDetailsMenuItem);

        MenuBar.add(detailsMenu);

        servicesMenu.setText("Services");
        servicesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesMenuActionPerformed(evt);
            }
        });

        servicesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        servicesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/servicesIcon.jpg"))); // NOI18N
        servicesMenuItem.setText("Services");
        servicesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesMenuItemActionPerformed(evt);
            }
        });
        servicesMenu.add(servicesMenuItem);

        MenuBar.add(servicesMenu);

        reportMenu.setText("Report");
        reportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportMenuActionPerformed(evt);
            }
        });

        reportMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        reportMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/reportIcon.jpg"))); // NOI18N
        reportMenuItem.setText("Report");
        reportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportMenuItemActionPerformed(evt);
            }
        });
        reportMenu.add(reportMenuItem);

        MenuBar.add(reportMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/about.jpg"))); // NOI18N
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        MenuBar.add(helpMenu);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void docDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docDetailsMenuItemActionPerformed
        // TODO add your handling code here:
        if(jDesktopPane.getComponentCount()>1)
            jDesktopPane.remove(jDesktopPane.getIndexOf(jDesktopPane.getSelectedFrame()));
        if(uID.equalsIgnoreCase("Admin")){
            DoctorScreenAdmin_GUI doc=new DoctorScreenAdmin_GUI();
            jDesktopPane.add(doc);
            doc.setVisible(true);
        }
        else{
            DoctorScreenLocal_GUI doc=new DoctorScreenLocal_GUI();
            jDesktopPane.add(doc);
            doc.setVisible(true);
        }
    }//GEN-LAST:event_docDetailsMenuItemActionPerformed

    private void patDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patDetailsMenuItemActionPerformed
        // TODO add your handling code here:
       if(jDesktopPane.getComponentCount()>1)
            jDesktopPane.remove(jDesktopPane.getIndexOf(jDesktopPane.getSelectedFrame()));
        PatDetails_GUI doc=new PatDetails_GUI();
        jDesktopPane.add(doc);
        doc.setVisible(true);
    }//GEN-LAST:event_patDetailsMenuItemActionPerformed

    private void servicesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesMenuActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_servicesMenuActionPerformed

    private void reportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportMenuActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        if(jDesktopPane.getComponentCount()>1)
            jDesktopPane.remove(jDesktopPane.getIndexOf(jDesktopPane.getSelectedFrame()));
        aboutScreen_GUI doc=new aboutScreen_GUI();
        jDesktopPane.add(doc);
        doc.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        statusLBL.setText("Logged in as "+uID);
        DefaultScreen_GUI doc=new DefaultScreen_GUI();
        jDesktopPane.add(doc);
        doc.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void homeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMenuItemActionPerformed
        // TODO add your handling code here:
        Main_GUI frame1=new Main_GUI();
        if(uID.equalsIgnoreCase("Admin")){
            frame1.setVisible(true);
            uID="Admin";
            frame1.uID=uID;
            this.dispose();
        }
        else{
            frame1.setVisible(true);
            uID="User";
            frame1.uID=uID;
            this.dispose();
        }
    }//GEN-LAST:event_homeMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void logOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutMenuItemActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login_GUI doc=new Login_GUI();
        doc.setVisible(true);
    }//GEN-LAST:event_logOutMenuItemActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    private void servicesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesMenuItemActionPerformed
        // TODO add your handling code here:
        if(jDesktopPane.getComponentCount()>1)
            jDesktopPane.remove(jDesktopPane.getIndexOf(jDesktopPane.getSelectedFrame()));
        servicesScreen s1=new servicesScreen();
        jDesktopPane.add(s1);
        s1.setVisible(true);
    }//GEN-LAST:event_servicesMenuItemActionPerformed

    private void reportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportMenuItemActionPerformed
        // TODO add your handling code here:
        if(jDesktopPane.getComponentCount()>1)
            jDesktopPane.remove(jDesktopPane.getIndexOf(jDesktopPane.getSelectedFrame()));
        reportScreen r1=new reportScreen();
        jDesktopPane.add(r1);
        r1.setVisible(true);
    }//GEN-LAST:event_reportMenuItemActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel copyrightLBL;
    private javax.swing.JMenu detailsMenu;
    private javax.swing.JMenuItem docDetailsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem homeMenuItem;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JMenuItem logOutMenuItem;
    private javax.swing.JMenuItem patDetailsMenuItem;
    private javax.swing.JMenu reportMenu;
    private javax.swing.JMenuItem reportMenuItem;
    private javax.swing.JMenu servicesMenu;
    private javax.swing.JMenuItem servicesMenuItem;
    private javax.swing.JLabel statusLBL;
    // End of variables declaration//GEN-END:variables

}
