
/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cbse_ip_project_hospital_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jithu G Panicker
 */
public class reportScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form reportScreen
     */
    public reportScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dcodeCB = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTBL = new javax.swing.JTable();
        closeBTN = new javax.swing.JButton();
        doc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(987, 508));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel1.setText("Select Doctor Code");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 16, 118, 19);

        dcodeCB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        dcodeCB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dcodeCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dcodeCBItemStateChanged(evt);
            }
        });
        dcodeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcodeCBActionPerformed(evt);
            }
        });
        getContentPane().add(dcodeCB);
        dcodeCB.setBounds(146, 11, 162, 29);

        reportTBL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reportTBL.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        reportTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor's Name", "Department", "Patient Code", "Patient Name", "Diagnosis", "Charges"
            }
        ));
        jScrollPane1.setViewportView(reportTBL);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 46, 951, 144);

        closeBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 15)); // NOI18N
        closeBTN.setText("CLOSE");
        closeBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });
        getContentPane().add(closeBTN);
        closeBTN.setBounds(841, 208, 120, 38);
        getContentPane().add(doc);
        doc.setBounds(320, 10, 180, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/report.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -30, 990, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dcodeCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dcodeCBItemStateChanged
        // TODO add your handling code here:
        String dc=(String)dcodeCB.getSelectedItem();
        DefaultTableModel dtm=(DefaultTableModel)reportTBL.getModel();
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db","root","pass");
            Statement stmt=(Statement)con.createStatement();
            String r="Select Doctor_Name,Department from docDetails where Doctor_Code='"+dc+"'";
            ResultSet rs=stmt.executeQuery(r);
            rs.first();
            String dname=rs.getString(1);
            String dept=rs.getString(2);
            doc.setText(dname+", "+dept);
            String r1="Select Patient_Code,Patient_Name,Diagnosis,Amount from patDetails where Doctor_Code='"+dc+"'";
            ResultSet rs1=stmt.executeQuery(r1);
            while(rs1.next()){
                Object nr[]={dname,dept,rs1.getString(1),rs1.getString(2),rs1.getString(3),rs1.getString(4)};
                dtm.addRow(nr);
            }
            rs.close();
            rs1.close();
            stmt.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_dcodeCBItemStateChanged

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeBTNActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db","root","pass");
            Statement stmt=(Statement)con.createStatement();
            String r1="Select distinct Doctor_Code from patDetails";
            ResultSet rs=stmt.executeQuery(r1);
            while(rs.next())
                dcodeCB.addItem(rs.getString(1));
            rs.close();
            stmt.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void dcodeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcodeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcodeCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBTN;
    private javax.swing.JComboBox dcodeCB;
    private javax.swing.JLabel doc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable reportTBL;
    // End of variables declaration//GEN-END:variables
}
