/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cbse_ip_project_hospital_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Livin
 */
public class servicesScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form servicesScreen
     */
    public servicesScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bloodTestRB = new javax.swing.JCheckBox();
        audiometryRB = new javax.swing.JCheckBox();
        sugarTestRB = new javax.swing.JCheckBox();
        endoscopyRB = new javax.swing.JCheckBox();
        eyeChckRB = new javax.swing.JCheckBox();
        tmtRB = new javax.swing.JCheckBox();
        urinalysisRB = new javax.swing.JCheckBox();
        xRayRB = new javax.swing.JCheckBox();
        ecgRB = new javax.swing.JCheckBox();
        colonoscopyRB = new javax.swing.JCheckBox();
        visaMedRB = new javax.swing.JCheckBox();
        mriScanRB = new javax.swing.JCheckBox();
        echoCardioRB = new javax.swing.JCheckBox();
        spyrometryRB = new javax.swing.JCheckBox();
        ultraSoundRB = new javax.swing.JCheckBox();
        ctScanRB = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pCode = new javax.swing.JTextField();
        amt = new javax.swing.JTextField();
        diagnosisCB = new javax.swing.JComboBox();
        calculateBTN = new javax.swing.JButton();
        billBTN = new javax.swing.JButton();
        closeBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        cancelBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        servicesTBL = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(987, 508));
        setMinimumSize(new java.awt.Dimension(987, 508));
        setPreferredSize(new java.awt.Dimension(987, 508));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Additional Charges"));

        bloodTestRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        bloodTestRB.setText("Blood Test (Rs.370)");
        bloodTestRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTestRBActionPerformed(evt);
            }
        });

        audiometryRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        audiometryRB.setText("Audiometry (Rs.690)");

        sugarTestRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        sugarTestRB.setText("Sugar Test (Rs.80)");

        endoscopyRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        endoscopyRB.setText("Endoscopy (Rs.2120)");

        eyeChckRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        eyeChckRB.setText("Eye Checkup (Rs.155)");
        eyeChckRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyeChckRBActionPerformed(evt);
            }
        });

        tmtRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        tmtRB.setText("TMT (Rs.2490)");
        tmtRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmtRBActionPerformed(evt);
            }
        });

        urinalysisRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        urinalysisRB.setText("Urinalysis (Rs.55)");
        urinalysisRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urinalysisRBActionPerformed(evt);
            }
        });

        xRayRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        xRayRB.setText("X-Ray (Rs.480)");
        xRayRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xRayRBActionPerformed(evt);
            }
        });

        ecgRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        ecgRB.setText("ECG (Rs.420)");
        ecgRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecgRBActionPerformed(evt);
            }
        });

        colonoscopyRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        colonoscopyRB.setText("Colonoscopy (Rs.2495)");
        colonoscopyRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colonoscopyRBActionPerformed(evt);
            }
        });

        visaMedRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        visaMedRB.setText("Visa Medical (Rs.1100)");
        visaMedRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaMedRBActionPerformed(evt);
            }
        });

        mriScanRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        mriScanRB.setText("MRI Scan (Rs.4230)");
        mriScanRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mriScanRBActionPerformed(evt);
            }
        });

        echoCardioRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        echoCardioRB.setText("Echocardiogram (Rs.2190)");
        echoCardioRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                echoCardioRBActionPerformed(evt);
            }
        });

        spyrometryRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        spyrometryRB.setText("Spyrometry (Rs.300)");
        spyrometryRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spyrometryRBActionPerformed(evt);
            }
        });

        ultraSoundRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        ultraSoundRB.setText("Ultrasonography (Rs.995)");
        ultraSoundRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultraSoundRBActionPerformed(evt);
            }
        });

        ctScanRB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        ctScanRB.setText("CT Scan (Rs.2930)");
        ctScanRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctScanRBActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eyeChckRB)
                    .addComponent(audiometryRB)
                    .addComponent(sugarTestRB)
                    .addComponent(endoscopyRB)
                    .addComponent(visaMedRB)
                    .addComponent(mriScanRB)
                    .addComponent(ctScanRB)
                    .addComponent(bloodTestRB))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tmtRB)
                    .addComponent(urinalysisRB)
                    .addComponent(xRayRB)
                    .addComponent(colonoscopyRB)
                    .addComponent(spyrometryRB)
                    .addComponent(ultraSoundRB)
                    .addComponent(echoCardioRB)
                    .addComponent(ecgRB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodTestRB)
                    .addComponent(tmtRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(audiometryRB)
                    .addComponent(urinalysisRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sugarTestRB)
                    .addComponent(xRayRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endoscopyRB)
                    .addComponent(ecgRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eyeChckRB)
                    .addComponent(colonoscopyRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(echoCardioRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spyrometryRB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(visaMedRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mriScanRB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ultraSoundRB)
                    .addComponent(ctScanRB)))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(550, 160, 410, 239);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Enter Data"));

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel1.setText("Patient Code");

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel3.setText("Treatment");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel4.setText("Amount");

        pCode.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        pCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pCodeFocusLost(evt);
            }
        });
        pCode.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pCodePropertyChange(evt);
            }
        });

        amt.setEditable(false);
        amt.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N

        diagnosisCB.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        diagnosisCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "General Surgery", "Keyhole Surgery", "Angioplasty", "Micro Surgery", "Neuro Surgery", "Cardiac Surgery", "Plastic Surgery", "Ear Surgery", "Thorasic Surgery", "Eye Surgery", "Abdominal Surgery" }));
        diagnosisCB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        diagnosisCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                diagnosisCBItemStateChanged(evt);
            }
        });
        diagnosisCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosisCBActionPerformed(evt);
            }
        });

        calculateBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 15)); // NOI18N
        calculateBTN.setText("CALCULATE");
        calculateBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calculateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBTNActionPerformed(evt);
            }
        });

        billBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 15)); // NOI18N
        billBTN.setText("BILL");
        billBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        billBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billBTNActionPerformed(evt);
            }
        });

        closeBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 15)); // NOI18N
        closeBTN.setText("CLOSE");
        closeBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });

        clearBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 15)); // NOI18N
        clearBTN.setText("CLEAR");
        clearBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        cancelBTN.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 19)); // NOI18N
        cancelBTN.setText("cancel");
        cancelBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(calculateBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(pCode, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(diagnosisCB, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(diagnosisCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 150, 310, 210);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel2.setText("Total Charges");

        total.setEditable(false);
        total.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        total.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 370, 310, 60);

        servicesTBL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        servicesTBL.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        servicesTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient_Code", "Patient_Name", "Doctor_Code", "Diagnosis", "Department", "Gender", "Amount"
            }
        ));
        jScrollPane1.setViewportView(servicesTBL);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 950, 132);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbse_ip_project_hospital_management/services.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, -20, 1000, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents
void refresh(){
     DefaultTableModel dtm=(DefaultTableModel)servicesTBL.getModel();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db","root","pass");
            Statement stmt=(Statement)con.createStatement();
            String str="Select * from patDetails";
            ResultSet rs=(ResultSet)stmt.executeQuery(str);
            while(dtm.getRowCount()>0){
                dtm.removeRow(0);
            }
            while(rs.next()){
                Object nr[]={rs.getString("Patient_Code"),rs.getString("Patient_Name"),rs.getString("Doctor_Code"),rs.getString("Diagnosis"),
                             rs.getString("Department"),rs.getString("Gender"),rs.getString("Amount")};
                dtm.addRow(nr);
            }
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
            }
        diagnosisCB.setSelectedIndex(0);
        amt.setText("0");
}

    void billOn(){
        bloodTestRB.setEnabled(false);
        audiometryRB.setEnabled(false);
        sugarTestRB.setEnabled(false);
        endoscopyRB.setEnabled(false);
        eyeChckRB.setEnabled(false);
        visaMedRB.setEnabled(false);
        mriScanRB.setEnabled(false);
        ctScanRB.setEnabled(false);
        tmtRB.setEnabled(false);
        urinalysisRB.setEnabled(false);
        closeBTN.setEnabled(false);
        xRayRB.setEnabled(false);
        ecgRB.setEnabled(false);
        colonoscopyRB.setEnabled(false);
        echoCardioRB.setEnabled(false);
        spyrometryRB.setEnabled(false);
        ultraSoundRB.setEnabled(false);
        billBTN.setEnabled(true);
        cancelBTN.setEnabled(true);
        pCode.setEnabled(false);
        diagnosisCB.setEnabled(false);
        clearBTN.setEnabled(false);
        calculateBTN.setEnabled(false);        
}
    
    void billOff(){
        bloodTestRB.setEnabled(true);
        audiometryRB.setEnabled(true);
        sugarTestRB.setEnabled(true);
        endoscopyRB.setEnabled(true);
        eyeChckRB.setEnabled(true);
        visaMedRB.setEnabled(true);
        mriScanRB.setEnabled(true);
        ctScanRB.setEnabled(true);
        tmtRB.setEnabled(true);
        urinalysisRB.setEnabled(true);
        xRayRB.setEnabled(true);
        ecgRB.setEnabled(true);
        colonoscopyRB.setEnabled(true);
        echoCardioRB.setEnabled(true);
        spyrometryRB.setEnabled(true);
        ultraSoundRB.setEnabled(true);
        billBTN.setEnabled(false);
        cancelBTN.setEnabled(false);
        pCode.setEnabled(true);
        diagnosisCB.setEnabled(true);
        clearBTN.setEnabled(true);
        calculateBTN.setEnabled(true);
        closeBTN.setEnabled(true);
        
            
        }
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        refresh();
        billOff();
           
    }//GEN-LAST:event_formInternalFrameOpened

    private void bloodTestRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTestRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTestRBActionPerformed

    private void eyeChckRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyeChckRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eyeChckRBActionPerformed

    private void tmtRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmtRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmtRBActionPerformed

    private void urinalysisRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urinalysisRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urinalysisRBActionPerformed

    private void xRayRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xRayRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xRayRBActionPerformed

    private void ecgRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecgRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecgRBActionPerformed

    private void colonoscopyRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colonoscopyRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colonoscopyRBActionPerformed

    private void visaMedRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaMedRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visaMedRBActionPerformed

    private void mriScanRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mriScanRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mriScanRBActionPerformed

    private void echoCardioRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_echoCardioRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_echoCardioRBActionPerformed

    private void spyrometryRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spyrometryRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spyrometryRBActionPerformed

    private void ultraSoundRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultraSoundRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ultraSoundRBActionPerformed

    private void ctScanRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctScanRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctScanRBActionPerformed

    private void diagnosisCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_diagnosisCBItemStateChanged
        // TODO add your handling code here:
        billOff();
        String treatment=(String)diagnosisCB.getSelectedItem();
        double amt1=0;
        if(treatment.equals("General Surgery"))
            amt1=50500;
        else if(treatment.equals("Keyhole Surgery"))
            amt1=121000;
        else if(treatment.equals("Angioplasty"))
            amt1=153000; 
        else if(treatment.equals("None"))
            amt1=0;
        else if(treatment.equals("Micro Surgery"))
            amt1=195000;
        else if(treatment.equals("Neuro Surgery"))
            amt1=180000; 
        else if(treatment.equals("Cardiac Surgery"))
            amt1=159000;
        else if(treatment.equals("Plastic Surgery"))
            amt1=354000;
        else if(treatment.equals("Ear Surgery"))
            amt1=43000; 
        else if(treatment.equals("Thorasic Surgery"))
            amt1=209000;
        else if(treatment.equals("Eye Surgery"))
            amt1=42000;
        else if(treatment.equals("Abdominal Surgery"))
            amt1=67000;
        amt.setText(""+amt1);
                        
    }//GEN-LAST:event_diagnosisCBItemStateChanged

    private void calculateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBTNActionPerformed
        // TODO add your handling code here:
        double amt1=Double.parseDouble(amt.getText());
        double tot=amt1;
        if(bloodTestRB.isSelected())
            tot+=370;
        if(audiometryRB.isSelected())
            tot+=690;
        if(sugarTestRB.isSelected())
            tot+=80;
        if(endoscopyRB.isSelected())
            tot+=2120;
        if(eyeChckRB.isSelected())
            tot+=155;
        if(visaMedRB.isSelected())
            tot+=1100;
        if(mriScanRB.isSelected())
            tot+=4230;
        if(ctScanRB.isSelected())
            tot+=2930;
        if(tmtRB.isSelected())
            tot+=2490;
        if(urinalysisRB.isSelected())
            tot+=55;
        if(xRayRB.isSelected())
            tot+=480;
        if(ecgRB.isSelected())
            tot+=420;
        if(colonoscopyRB.isSelected())
            tot+=2495;
        if(echoCardioRB.isSelected())
            tot+=2190;
        if(spyrometryRB.isSelected())
            tot+=300;
        if(ultraSoundRB.isSelected())
            tot+=995;
        total.setText(""+tot);
        billOn();
        
    }//GEN-LAST:event_calculateBTNActionPerformed

    private void billBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billBTNActionPerformed
        // TODO add your handling code here:
        String pc=pCode.getText();
        String diagnosis=(String)diagnosisCB.getSelectedItem();
        double tot=Double.parseDouble(total.getText());
        if(pc.equals(""))
            JOptionPane.showMessageDialog(this,"Enter Patient Code");
        else{
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagement_db","root","pass");
            Statement stmt=(Statement)con.createStatement();
            String str="Select Patient_Code from patDetails";
            String str1="Update patdetails set treatment='"+diagnosis+"',amount=(amount+"+tot+") where Patient_Code="+pc;
            stmt.executeUpdate(str1);
            ResultSet rs=(ResultSet)stmt.executeQuery(str);
            while(rs.next()){
                if(pc.equalsIgnoreCase(rs.getString(1)))
                    break;
            }
            if(rs.isAfterLast())
                JOptionPane.showMessageDialog(rootPane,pc+" is not found in the database");
            rs.close();
            stmt.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        refresh();
        billBTN.setEnabled(false);
        clearBTN.doClick();
        }
        billOff();
    }//GEN-LAST:event_billBTNActionPerformed

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        billOff();
        bloodTestRB.setSelected(false);
        audiometryRB.setSelected(false);
        sugarTestRB.setSelected(false);
        endoscopyRB.setSelected(false);
        eyeChckRB.setSelected(false);
        visaMedRB.setSelected(false);
        mriScanRB.setSelected(false);
        ctScanRB.setSelected(false);
        tmtRB.setSelected(false);
        urinalysisRB.setSelected(false);
        xRayRB.setSelected(false);
        ecgRB.setSelected(false);
        colonoscopyRB.setSelected(false);
        echoCardioRB.setSelected(false);
        spyrometryRB.setSelected(false);
        ultraSoundRB.setSelected(false);
        pCode.setText("");
        total.setText("");
        diagnosisCB.setSelectedIndex(0);

    }//GEN-LAST:event_clearBTNActionPerformed

    private void diagnosisCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosisCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosisCBActionPerformed

    private void cancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTNActionPerformed
        // TODO add your handling code here:
        billOff();
        clearBTN.doClick();
    }//GEN-LAST:event_cancelBTNActionPerformed

    private void pCodePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pCodePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_pCodePropertyChange

    private void pCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pCodeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pCodeFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.JCheckBox audiometryRB;
    private javax.swing.JButton billBTN;
    private javax.swing.JCheckBox bloodTestRB;
    private javax.swing.JButton calculateBTN;
    private javax.swing.JButton cancelBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton closeBTN;
    private javax.swing.JCheckBox colonoscopyRB;
    private javax.swing.JCheckBox ctScanRB;
    private javax.swing.JComboBox diagnosisCB;
    private javax.swing.JCheckBox ecgRB;
    private javax.swing.JCheckBox echoCardioRB;
    private javax.swing.JCheckBox endoscopyRB;
    private javax.swing.JCheckBox eyeChckRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox mriScanRB;
    private javax.swing.JTextField pCode;
    private javax.swing.JTable servicesTBL;
    private javax.swing.JCheckBox spyrometryRB;
    private javax.swing.JCheckBox sugarTestRB;
    private javax.swing.JCheckBox tmtRB;
    private javax.swing.JTextField total;
    private javax.swing.JCheckBox ultraSoundRB;
    private javax.swing.JCheckBox urinalysisRB;
    private javax.swing.JCheckBox visaMedRB;
    private javax.swing.JCheckBox xRayRB;
    // End of variables declaration//GEN-END:variables
}
